### ISSUE TITLE
How to use AzPainter as image viewer?

### ISSUE THREAD

**Issue by dellus** [Symbian9/azpainter#101]
This is less an issue but more a wishue.
I have always been longing for a Linux equivalent to Irfanview for Windows. A small, efficient and versatile viewer / editor combo. There is xnview mp, ok, but large, and not open source.
I am on PuppyLinux, a lightweight fast OS and recently stumbled onto azpainter. Small, efficient, fits Puppy very well. I discovered the Show panels button, which clears the screen from most editing panels. If only Next / Previous buttons were added azpainter would make a wonderful viewer / editor combo. Additional features like lossless jpg rotation and cropping, use of 8bf filters and some more file formats could be added later.
I am not a coder but I imagine these two buttons would be rather easy to implement. Not really something new to develop but just sticking together existing components in a different way. But maybe I am wrong.

**Comment by Symbian9** [comment]
> This is less an issue but more a wishue.

We call it "feature request" ;)

> Not really something new to develop

Did you know AzPainter already has "Image viewer" (go to menu "View (V) > Panel (P) > Image viewer (I)" to activate/deactivate it); then you may separate "Image viewer" from main window layout & maximize its window and use as image editor. That's it!

No any additional patches are needed ;)

FTR, If this instruction looks is not fully complete, I may add step-by-step screenshots (but tomorrow).

**Comment by dellus** [comment]
Thanks for the quick response.
I have indeed not noticed the Image viewer feature, it's a bit hidden. Nice to have, but to be honest, not really what I have been seeking.
I would like to have Previous / Next buttons directly in the main Toolbar, best last after the Release selection button to be easily found and hit. It should then close the present image and open the next or previous image in the folder. 
If no change has occurred it can do so instantly, if there was a change it should ask whether to save it before. In Irfanview you are not asked that, so you can easily lose your editing work accidentally if you don't think of saving it by yourself.
With this layout you don't have to switch to an extra viewer mode / window, it's one workflow.
From the now existing viewer window you can't even load the image into the main editing window, and it doesn't show the filename. Kind of blind flight.
So I'm still hoping for fulfilment of my desire.

Yours  - dellus

**Comment by Symbian9** [comment]
> not really what I have been seeking.

You may send your request on "image viewer" creating as separate app to *Azel* (main developer of AzPainter)

- E-mail: ![`azelpg AT gmail DOT com`](http://azsky2.html.xdomain.jp/mail.png)
- Mail Form: https://form1ssl.fc2.com/form/?id=41eb1dd3b023f4c0

> From the now existing viewer window you can't even load the image into the main editing window, and it doesn't show the filename.

I may agree on this case, but this is a subject for a separate issue/feature request thread.

**Comment by dellus** [comment]
Again thanks for your quick response.
Maybe there is a misunderstanding of my aim. I do not want the image viewer as a separate app. All I wish is to have a mechanism to open the next or previous image file in a folder just by clicking on a next or previous button (or equivalent keys on the keyboard) instead of having to go to Open and browse to that file to select it and so on. Otherwise same procedure as is. 
Yes, I will contact main developer Azel, maybe best approach.

Yours - dellus

**Comment by Symbian9** [comment]
> Maybe there is a misunderstanding of my aim. I do not want the image viewer as a separate app.

If so I may close this issue thread.

> All I wish is...

This feature request moved to https://github.com/Symbian9/azpainter/issues/102
