### ISSUE TITLE
Azpainter segmentation fault on Raspberry Pi

### ISSUE THREAD

**Issue by geo-historia** [Symbian9/azpainter#104]
First of all, I'm on a Pi 400. The program itself seems to have installed without any problems, its icon even shows up in the graphics tab: 
![azpainter1](https://user-images.githubusercontent.com/71405453/108182583-749ca780-7109-11eb-8c25-2e75887c66b5.jpg)

The thing is, when I click on it nothing happens. I tried running it from the terminal but this happens:
![Captura de pantalla de 2021-02-17 10-15-26](https://user-images.githubusercontent.com/71405453/108182240-17085b00-7109-11eb-8881-468b68e9b5d5.png)
"Segmentation fault"

I followed the README to install it so I'm not sure what could have gone wrong, any ideas? Sorry if this is a dumb issue, I'm still new to Linux in general.

**Comment by Symbian9** [comment]
> any ideas?

What AzPainter version you use?

> I followed the README to install

JFTR, It would be better to ask somewhere on Raspberry Community forums/Reddit does it affects other RPi users.

I'm not a RPi user, so can't tell nothing at this moment.

**Comment by geo-historia** [comment]
I installed 2.1.5. And I'll ask around, see what I can find.

**Comment by Symbian9** [comment]
> I installed 2.1.5

@geo-historia, `2.1.5` is pretty outdated and has some known issues which are resulted in segmentation faults.

Try compile & install `2.1.7`:

1. Tarball - http://azsky2.html.xdomain.jp/arc/azpainter-2.1.7.tar.xz
2. Updated locales (same as in `2.1.6`):
2.1. https://github.com/Symbian9/azpainter/tree/master/translation
2.2. https://github.com/Symbian9/azpainter/tree/master/data/tr

**Comment by geo-historia** [comment]
Installing 2.1.7 did the trick, thank you!

**Comment by Symbian9** [comment]
> Installing 2.1.7 did the trick, thank you!

Thank You for feedback! Happy to know it works for You now ;)

JFTR, @geo-historia, may You share **photo** and **screenshot** of your *RaspberryPi device with AzPainter launched*?

**Comment by geo-historia** [comment]
No problem! Here's a screenshot:
![Captura de pantalla de 2021-03-01 20-50-23](https://user-images.githubusercontent.com/71405453/109551234-9403df00-7ad0-11eb-8a55-8a0dde8ce664.png)

And here's a photo of my (rather messy) setup:
![WhatsApp Image 2021-03-01 at 20 59 32](https://user-images.githubusercontent.com/71405453/109551676-25735100-7ad1-11eb-9cfd-6da74c902e5c.jpeg)
