### ISSUE TITLE
Another round of translation fixes

### ISSUE THREAD

**Issue by danfe** [Symbian9/azpainter#11]
Not too much this time, just a few minor typos.  See attached [patch](https://github.com/Symbian9/azpainter/files/1272177/translation-fixes.txt).

**Comment by Symbian9** [comment]
@danfe, Could you create pull request for this task?

**Comment by Symbian9** [comment]
Fixed with some changes added.
* https://github.com/Symbian9/azpainter/commit/e9f7b06a4ac7a64a7ae0dc20210d0f2d1d6b2b28

**Rebuild your package again** if all OK!

**Comment by danfe** [comment]
Proposed changes committed as of e9f7b06, closing.
