### ISSUE TITLE
Hi, add, please, Belarusian language

### ISSUE THREAD

**Issue by antikruk** [Symbian9/azpainter#35]
[be.zip](https://github.com/Symbian9/azpainter/files/1913512/be.zip)

**Comment by Symbian9** [comment]
@antikruk, need check: `Размыццё гаўса...`.

Maybe, it should be: `Размыццё Гаўса...`?

**Comment by antikruk** [comment]
Yes

**Comment by Symbian9** [comment]
Fixed & merged: https://github.com/Symbian9/azpainter/commit/70f9c02ecc6b982354b75e6842965d60940c1861
