### ISSUE TITLE
Preparing for packaging AzPainter 2.1.0

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#4]
**Use sources of v2.1.0 release!**
* https://github.com/symbian9/azpainter/releases/tag/v2.1.0

Cast @probonopd
* [ ] Linux-based (.AppImage)
  * https://bintray.com/probono/AppImages/AzPainter/_latestVersion#files
  * [x] setup autobuilds using Travis CI 
    * [ ] upload resulted binary in "Releases"
    * [ ] setup autoupload resulted binary in "Releases"

Cast @AlexanderP
* [x] Debian (.deb)
  * http://notesalexp.org/packages/en/jessie/amd64/azpainter/
* [x] Ubuntu (.deb)
  * https://launchpad.net/~alex-p/+archive/ubuntu/azpainter

Cast @abcang
* [ ] macOS (.dmg)

Cast @danfe
* [x] FreeBSD (ports)
  * http://www.freshports.org/graphics/azpainter

Cast @aevseev
* [ ] CentOS (.rpm)
  * http://download.opensuse.org/repositories/home:/aevseev/

P.S.: Unknown users
* [x] Arch Linux (AUR)
  * https://aur.archlinux.org/packages/azpainter/
* [ ] Gentoo (.ebuild)
  * https://gpo.zugaina.org/media-gfx/azpainter
* [x] MX Linux (.deb)
  * http://mxrepo.com/mx/testrepo/pool/test/a/azpainter/
* [ ] Puppy Linux (.pet/.sfs)
  * http://www.murga-linux.com/puppy/viewtopic.php?t=95329
* [ ] Slackware (.tgz/.txz)
* [ ] SliTaZ (.tazpkg)
  * http://forum.slitaz.org/topic/azpainter-why-it-isnt-in-slitaz-repositories
* [ ] Void Linux (.xbps)

P.S.: check `master` branch of AzPainter (currently 2.1.0) for mistakes and ask me before packaging using this repository.

REFERENCE:
* https://repology.org/metapackage/azpainter/versions
* https://pkgs.org/download/azpainter
* https://www.linux.org.ru/forum/multimedia/13223232

**Comment by probonopd** [comment]
I can do something once the trusty ppa is available

**Comment by probonopd** [comment]
I need to correct myself: Since the source code is now on GitHub, do we want a) re-package the debs from the trusty ppa into AppImages (as we did in the past), or do we want b) continuous builds for each git push, e.g., using Travis CI or the Open Build Service?

**Comment by AlexanderP** [comment]
+ Ubuntu (.deb)

https://launchpad.net/~alex-p/+archive/ubuntu/azpainter

2017-08-31 21:49 GMT+03:00 probonopd <notifications@github.com>:

**Comment by Symbian9** [comment]
> continuous builds for each git push, e.g., using Travis CI or the Open Build Service?

@probonopd, I prefer this way ;-)

Could you help setup this repo for build binary using Travis CI?

I would be happy if someone also help me setup OBS for build binary AppImage + packages (for each distributive) like it work for OpenOrienteering Mapper
* http://github.com/openorienteering/mapper
  * https://download.opensuse.org/repositories/home:/dg0yt/

**Comment by Symbian9** [comment]
I just make a release of 2.1.0 for better interaction
* https://github.com/Symbian9/azpainter/releases/tag/v2.1.0

**Comment by AlexanderP** [comment]
+ Debian (deb)

@Symbian9 verified

2017-09-01 2:06 GMT+03:00 AppSoft4 <notifications@github.com>:

**Comment by Symbian9** [comment]
macOS port ready!
- https://github.com/abcang/azpainter-mac/releases/tag/2.1.0

https://twitter.com/abcang1015/status/943838453506088960
