### ISSUE TITLE
Up zh_CN chinese translation for AzPainter-2.1.3

### ISSUE THREAD

**Issue by SenlinOS** [Symbian9/azpainter#44]
Up zh_CN chinese translation for AzPainter-2.1.3

It is 100% translation.
[zh_CN-2.1.3](https://github.com/SenlinOS/warehouse/raw/master/zh_CN-Chinese-Translation-for-AzPainter-2.1.3.zip)
There are two files in Zip: zh_CN & zh_CN.mtr
zh_CN is a translation file.
zh_CN.mtr is a translation application file. (sudo cp zh_CN.mtr /usr/local/share/azpainter/tr)

**Comment by imzf** [comment]
@SenlinOS cool(*˘︶˘*).｡.:*♡

**Comment by Symbian9** [comment]
@SenlinOS, Thank You!

I will update `master` to `2.1.3` today ;-)

**Comment by Symbian9** [comment]
Let's discuss process of updating locales for *AzPainter 2.1.3* here:

- https://github.com/Symbian9/azpainter/issues/45
