### ISSUE TITLE
Can't specify workspace for AzPainter

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#49]
Posted on OSDN:
- https://osdn.net/review/124264

> **Review by Speyll, 2018-11-07 01:59**
> 
> Great software, Lightweight and responsive works great with my Wacom intuos tablet, but i'm currently using Arch + i3wm and i wanted to specify a workspace for AzPainter, but when doing a `xprop` or `xprop WM_CLASS`, the software does not have a `Class`, so i think it's a bug if the team can do somthing about it it would be great!

**Comment by Symbian9** [comment]
@azelpg, does it fixed with latest changes in your repo?

**Comment by azelpg** [comment]
Yes, WM_CLASS has been set in 2.1.6.
