### ISSUE TITLE
Up zh_CN chinese translation for AzPainter-2.1.4

### ISSUE THREAD

**Issue by SenlinOS** [Symbian9/azpainter#57]
Up zh_CN chinese translation for AzPainter-2.1.4

It is 100% translation.
[zh_CN-2.1.4](https://github.com/SenlinOS/warehouse/raw/master/zh_CN-Chinese-Translation-for-AzPainter-2.1.4.zip)
There are two files in Zip: zh_CN & zh_CN.mtr
zh_CN is a translation file.
zh_CN.mtr is a translation application file. (sudo cp zh_CN.mtr /usr/local/share/azpainter/tr)

**Comment by Symbian9** [comment]
> AzPainter-2.1.4

Thanks for the notification!

Now I'm working on merging `v2.1.4` in `dev` branch.
