### ISSUE TITLE
Appimage does not load translation files.

### ISSUE THREAD

**Issue by zhoujin7** [Symbian9/azpainter#68]
$ locale
```bash
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
```

Click run the appimage, the UI language is English, not Chinese (zh_CN).

**Comment by Symbian9** [comment]
I not sure that understand described issue. Could you give more details and step-by-step instruction to reproduce?

FTR, AppImage build is not recommended to use at this moment.

**Comment by zhoujin7** [comment]
OS: Linux Mint 19.2 Cinnamon
locale: zh_CN
https://github.com/Symbian9/azpainter/blob/master/translation/HOWTO_en
```
Now, because of the system of the language file is opened in default
at the time of start-up, if the system is en_US en_US.mtr is loaded.
```

**Actual:**
![1](https://user-images.githubusercontent.com/8288988/69909851-66973400-143c-11ea-8fd1-d2c14e43ad13.png)

**expected:**
![2](https://user-images.githubusercontent.com/8288988/69909852-6bf47e80-143c-11ea-93f4-029a4ab8c87e.png)

Another problem, Tool icon is missing.
![3](https://user-images.githubusercontent.com/8288988/69909889-fb019680-143c-11ea-869a-729009254508.png)

**Comment by Symbian9** [comment]
> Another problem

I see. This is known problems of AppImage build. So, please, do not use it now!

- https://github.com/Symbian9/azpainter/issues/42

> OS: Linux Mint 19.2 Cinnamon

@zhoujin7 Install *AzPainter* from *alex-p*'s PPA (for Linux Mint 19.2 Cinnamon you need DEB targeted to Ubuntu 18.04 Bionic):

- https://notesalexp.org/packages/en/bionic/amd64/azpainter/
- mirror - https://launchpad.net/~alex-p/+archive/ubuntu/azpainter/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic

The best way is to enable this PPA in your package manager, details on this page:

- https://notesalexp.org
