### ISSUE TITLE
Official AzPainter repo on GitHub (WIP)

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#81]
> NOTE: As my repo is un-official, in most cases it already used for packaging by most of package maintainers.

@azelpg, main developer of *AzPainter*, now started working on creating official repo on GitHub

- https://github.com/azelpg/azpainter

I don't know how would be next dev process organized yet. Should I transfer all issues to this new repo?

Please, @azelpg, add more details on next development in comments here!

**Comment by azelpg** [comment]
Sorry... AzPainter's next development is still a long way off.
Probably more than a year away.
I think that the next version will have many changes, so I will make it alone until it is completed.

**Comment by Symbian9** [comment]
> I think that the next version will have many changes, so I will make it alone until it is completed.

Thanks for details! So, I will continue to maintain this repo.

@azelpg, would you regular merge updates (fixed locales, etc.) from my repo to your repo yourself OR should I create pull requests to you repo?

**Comment by azelpg** [comment]
I want to update myself if necessary.
Thank you.

**Comment by Symbian9** [comment]
Will close this issue due to *Azel* removed own profiles from GitHub (and earlier from OSDN):

- ~~https://github.com/azelpg/~~
- ~~https://osdn.net/users/azelpg/~~

Official downloads now hosted on official website:

- http://azsky2.html.xdomain.jp/arc/download.html
