### ISSUE TITLE
Can't save brushes. 

### ISSUE THREAD

**Issue by muevoid** [Symbian9/azpainter#85]
Hello! I am quite fond of this program however brushes I make and or import via pasting I cannot save even after hitting the save icon. I am on KISS linux and have packaged it myself however I use the normal compile options and everything else seems to work fine other then saving brushes. Any help is appreciated.

**Comment by Symbian9** [comment]
What version of AzPainter you use?

Cast @azelpg

**Comment by muevoid** [comment]
2.1.5

**Comment by Symbian9** [comment]
> `2.1.5`

Could you try compile & install from `dev` branch?

- https://github.com/Symbian9/azpainter/tree/dev

(this branch would be used to form `2.1.6` release this week; WIP)

> I am on KISS Linux

@dylanaraps could you check it?

- https://github.com/Symbian9/azpainter/wiki/Brushes#copy-paste-and-overwrite-brushes

**Comment by muevoid** [comment]
I have done that it still seems to not save any new brushes however I could also be doing something wrong. To add a new brush I simply paste in the brush code by hitting the arrow and hitting paste new brush correct? Then press the save icon next to the name or am I missing something?

**Comment by Symbian9** [comment]
> however I could also be doing something wrong.

Could you record screencast video and list all steps to reproduce?

I still has no clear understanding what you are try do:

- Save changes to selected brush?

OR

- Paste new brush from clipboard?

**Comment by muevoid** [comment]
Sorry I am not quite good at wording things sometimes the problem is I paste in a new brush then I can draw a drawing but If I exit the program and relaunch it it won't save any new brushes I created or made in the last session.

**Comment by Symbian9** [comment]
> I paste in a new brush then I can draw a drawing but If I exit the program and relaunch it it won't save any new brushes I created or made in the last session.

Please, record screencast to show all steps you acted to change/paste/save brushes in AzPainter.

To record screencast I would recommend next apps:

- https://github.com/MaartenBaert/ssr
- https://github.com/vkohaupt/vokoscreenNG

**Comment by muevoid** [comment]
Here you go:

**Comment by muevoid** [comment]
Here you go:

**Comment by muevoid** [comment]
Here you go: https://m.imgur/com/a/JjVrch9

**Comment by Symbian9** [comment]
> Here you go: ~~https://m.imgur.com/a/JjVrch9~~ -> https://imgur.com/ZOr2fij

Thanks.

I can NOT reproduce this issue under Debian 10 buster / Xfce.

@muevoid Possibly, this is your environment or KISS Linux issue, but seems like not AzPainter itself.

Please, report your issue to KISS Linux devs too:

- https://github.com/kisslinux/community/issues/153

**Comment by muevoid** [comment]
This issue can be closed it is due to sowm not asking to close windows before hand which is intended however there is a patch I am using that has fixed this issue.

**Comment by Symbian9** [comment]
> due to sowm not asking to close windows before hand which is intended however there is a patch I am using that has fixed this issue.

So, this is just WM/DE environment issue, right?

**Comment by muevoid** [comment]
Yep and talked to dylan(the maintainer of sowm) he is merging it so the wm request to shut down instead of force closing so this shouldnt be an issue in the near future.
