### ISSUE TITLE
Configure script broken

### ISSUE THREAD

**Issue by ibara** [Symbian9/azpainter#88]
`$ ./configure CFLAGS="-O2 -pipe"`
configure: line 205: -pipe: command not found

And then it doesn't pick up any of the CFLAGS listed on the command line.

**Comment by Symbian9** [comment]
> ```
> $ ./configure CFLAGS="-O2 -pipe"
> configure: line 205: -pipe: command not found
> ```

Seems like previous build configuration are obsolete for `v2.1.6`. Try review your build configuration by looking inside latest `Makefile.in` & `configure`:

- https://github.com/Symbian9/azpainter/blob/master/Makefile.in
- https://github.com/Symbian9/azpainter/blob/master/configure

Cast @azelpg.

**Comment by ibara** [comment]
Sure, and I have. But that's not actually the issue in #88. The issue is that the configure script is broken. It claims to support environment variables, but it in fact does not (you cannot do something like env CFLAGS='-O3' ./configure, it will not work). It accepts some non-standard arguments (CC, CFLAGS, etc.) and even then, does not support those non-standard arguments correctly (since ./configure CFLAGS="-O2 -pipe" is broken as well).

If not using autotools is desired, my autotools-less configure script for oksh does support environment variables correctly:
https://github.com/ibara/oksh/blob/master/configure

**Comment by ibara** [comment]
To be clear, it doesn't matter to me which form azpainter uses. It can be either `env CFLAGS='-O2 -pipe' ./configure` or `configure CFLAGS='-O2 -pipe'` and either one would be totally OK.

**Comment by Symbian9** [comment]
> The issue is that the configure script is broken
>
> my autotools-less 

I would be happy if AzPainter would use "autotools-less" build configuration, but it depend on @azelpg choice.

So, lets wait on Azel for this issue solution.

**Comment by azelpg** [comment]
I updated configure.
