### ISSUE TITLE
No stable tarball

### ISSUE THREAD

**Issue by ibara** [Symbian9/azpainter#89]
If this is going to be the place where packagers are asked to build packages from, having stable tarballs would be nice. The auto-generated tarballs (aka "Source code (.tar.gz)" and "Source code (.zip)" files) have been known to change over time, which causes all sorts of headaches for packagers.

Uploading a tarball for each release will mitigate that issue.

**Comment by Symbian9** [comment]
> If this is going to be the place where packagers are asked to build packages from, having stable tarballs would be nice.

Just added as `azpainter-2.1.6.tar.xz` asset.

Is it OK now?

**Comment by ibara** [comment]
Yes, that is good. Thank you!
