### ISSUE TITLE
Where are brushes and icont theme support?

### ISSUE THREAD

**Issue by blue-devil-93** [Symbian9/azpainter#97]
Hi,

modded the icon theme a bit myself: 
Don`t know what  has been done with the original, the purely black and white is not very usable to me. 
Not only is it obnly b/w also the icons are very unreadable.  Use gimp and jasc paint shop pro and photoline too.

![screenshot](https://user-images.githubusercontent.com/59343188/88449815-5c51fc00-ce4a-11ea-8ba6-b0d4a36cc7f2.png)

Did make one brush on my own:
![sharp-brush](https://user-images.githubusercontent.com/59343188/88449831-7d1a5180-ce4a-11ea-8541-eb20b2b18080.png)

azpainter-v2-brush;name=Charc%2Doil;type=2;radius=10.0;radius_min=0.3;radius_max=400.0;opacity=100;pix=0;sm_type=1;sm_str=1;min_size=0.0;min_opacity=100.0;interval=0.20;rand_size=100.0;rand_pos=0.00;angle=0;angle_rand=0;rough=0;hard=100;flags=4;water1=50.0;water2=90.0;water3=40.0;press_type=0;press_value=25;shape=sharp%2Dbrush%2Epng;texture=%3F;

The picture in the screenshot is made with that brush
The application itself is very good and working blazingly fast. 
Is there a way to add language support.?

kind regards blue-devil-93

**Comment by Symbian9** [comment]
> Where are brushes and icont theme support?

I not see what is wrong according issue title in your comment above. Custom icons & brushes already supported:

- https://github.com/Symbian9/azpainter/wiki/Brushes
- https://github.com/Symbian9/azpainter/wiki/Themes

> Is there a way to add language support?

Could you add more details on what you mean under *"add language support"*?

*AzPainter* already support various languages & include more than 15 locales. If you want to help in improving exists locales OR want to add new locale, feel free to join translation team! Here is related issue thread for translators:

- https://github.com/Symbian9/azpainter/issues/84

> `azpainter-v2-brush;name=Charc%2Doil;type=2;radius=10.0;radius_min=0.3;radius_max=400.0;opacity=100;pix=0;sm_type=1;sm_str=1;min_size=0.0;min_opacity=100.0;interval=0.20;rand_size=100.0;rand_pos=0.00;angle=0;angle_rand=0;rough=0;hard=100;flags=4;water1=50.0;water2=90.0;water3=40.0;press_type=0;press_value=25;shape=sharp%2Dbrush%2Epng;texture=%3F;`

Thanks for submitting `Charc-oil` brush!

I will add it to *«Community Brushes»* on *«Brushes»* wiki page, but, **please, upload also brush shape image** (`sharp-brush.png` file) required by this brush.

**Comment by blue-devil-93** [comment]
This image here is the sharp-brush.png
![sharp-brush](https://user-images.githubusercontent.com/59343188/88661243-7f91db00-d0d8-11ea-95b9-95663efa6d1d.png)

Also as link:
https://www.bilder-upload.eu/upload/8fa7d6-1595936812.png

The result looks like this:
![Charc-oil](https://user-images.githubusercontent.com/59343188/88661287-8f112400-d0d8-11ea-80ee-3f1e931e1ea3.png)

**Comment by blue-devil-93** [comment]
Issue can be closed, since translation file has been send and sharp-brush.png provided,

**Comment by Symbian9** [comment]
> This image here

Thanks!
